from typing import Protocol, runtime_checkable

from dicechanics import protocols


@runtime_checkable
class Bag(Protocol):
	def inside(self): ...

	def keys(self): ...

	def values(self): ...

	def items(self): ...
	def __bool__(self): ...

	def __add__(self, rhs: protocols.Mapping | "Bag"): ...
