from typing import Protocol, runtime_checkable


@runtime_checkable
class Unit(Protocol):
	def __add__(self, lhs): ...

	# def __sub__(self, lhs): ...
	# def __mul__(self, lhs): ...
	# def __div__(self, lhs): ...
	# def __truediv__(self, lhs): ...
