@startuml core
top to bottom direction
package "core"{
    class DefaultCollection{
    }
    interface "Collection" as collection {
        container of bags, used for combinatorial calulations\nrelated to Group-Group interaction
        bags are created seperately
        + prepare() -> Iterable[(Group, count)]
    }
    class DefaultGroup{
    }
    interface "Group" as group{
        container of mappings, used for\nspecific combinatorial calulations
        mappings are created seperatly
        + prepare() -> Iterable[(Mapping, bool)]
        + prepareSlice() -> Slice
        + __getitem__(Python.slice):
    }
    interface "CombinationsMapping" as mapping{
        Basic backend type for combinatorial calculations,\nif the methods are defined then its good for use.
        + items()
        + keys()
        + values()
    }
    Class "Slice" as sliceClass
    interface "Slice" as slice{
        +Slice(mask: Sequence[int])
        +Slice(mask: python slice)
        +next()
        +prev()
    }
    interface GroupCombinations {
        calculate(Group, operation) 
    }
    class RegularCombinations{
        
    }
    class SelectiveCombinations{
        
    }
}

DefaultCollection ..|> collection
collection --> group
DefaultGroup ..|> group
group --> mapping
group --> slice: for selective
sliceClass ..|> slice
GroupCombinations --> group
RegularCombinations ..|> GroupCombinations
SelectiveCombinations ..|> GroupCombinations
@enduml