@startuml Dicechanics
top to bottom direction
package "Dicechanics" {
    class Die{
    }
    class "Number Statistical" as numstat
    class "String Statistical" as strstat
    class "Base Statistical" as basestat
    class PoolImpl
    class BagImpl
    interface Statistical{
        + items()
        + keys()
        + values()
        + map()
        + normalize()
        + mean
        + std
        + varians
    }
    interface "Die" as die{
        + {method}<<Die manipulation functions>>
        + {method}<<Operator overloads>>
        + map(callable)
        + mean
        + std
        + varians
    }
    interface Pool{
        + extend(Die)
        + {method} <<Operator Overloads>>
    }
    interface Bag
}

package "Core"{
    interface mapping
    interface collection
    interface group
    class DefaultCollection
    class DefaultGroup
    class DefaultMap
}

Die .left.|> die
Die --> Statistical 
die --|> mapping
numstat .up.|> Statistical
strstat .up.|> Statistical
basestat .up.|> Statistical
numstat -down-|> basestat: special\ncase of 
strstat -down-|> basestat: special\ncase of
Pool -left-|> group
Pool ..> die
PoolImpl .left.|> Pool
PoolImpl -right-|> DefaultGroup
Bag -right-|> collection
BagImpl .left.|> Bag
BagImpl -right-|> DefaultCollection
Bag .down.> Pool
Die -|> DefaultMap


'Core
DefaultCollection .|> collection
DefaultGroup .|> group
DefaultMap .|> mapping
collection -down-> group
group -down-> mapping
@enduml