@startuml
[6:3] -> [5:3]:leftToChoose = 0
[6:3] -> [5:3]:leftToChoose = 1
[6:3] -> [5:3]:leftToChoose = 2
[6:3] -> [5:3]:leftToChoose = 3

[5:3] -> [4:3]:leftToChoose = 0
[5:3] -> [4:3]:leftToChoose = 1
[5:3] -> [4:3]:leftToChoose = 2
[5:3] -> [4:3]:leftToChoose = 3

[4:3] -> [3:3]:leftToChoose = 0
[4:3] -> [3:3]:leftToChoose = 1
[4:3] -> [3:3]:leftToChoose = 2
[4:3] -> [3:3]:leftToChoose = 3

[3:3] -> [2:3]:leftToChoose = 0
[3:3] -> [2:3]:leftToChoose = 1
[3:3] -> [2:3]:leftToChoose = 2
[3:3] -> [2:3]:leftToChoose = 3

[2:3] -> [1:3]:leftToChoose = 0
[2:3] -> [1:3]:leftToChoose = 1
[2:3] -> [1:3]:leftToChoose = 2
[2:3] -> [1:3]:leftToChoose = 3

[1:3] -> [None]:leftToChoose = 0
[1:3] -> [None]:leftToChoose = 1
[1:3] -> [None]:leftToChoose = 2
[1:3] -> [None]:leftToChoose = 3
@enduml