@startuml parser
top to bottom direction
hide empty description
state first_char
state expand
state repeat
[*] --> first_char : Legal char
first_char --> first_char : legal char
first_char --> expand : '..'
first_char --> [*] : No '..' or ':'
first_char --> repeat : ':'
expand --> repeat: ':'
expand --> [*]: no ':'
expand --> expand : legal char
repeat -->repeat : legal char
repeat --> [*] : EOF


@enduml