@startuml System
top to bottom direction
package "core"{
    class DefaultCollection{
    }
    interface "Collection" as collection {
        container of bags, used for combinatorial calulations\nrelated to Group-Group interaction
        bags are created seperately
        + prepare() -> Iterable[(Group, count)]
    }
    class DefaultGroup{
    }
    interface "Group" as group{
        container of mappings, used for\nspecific combinatorial calulations
        mappings are created seperatly
        + prepare() -> Iterable[(Mapping, bool)]
        + prepareSlice() -> Slice
        + __getitem__(Python.slice):
    }
    interface "CombinationsMapping" as mapping{
        Basic backend type for combinatorial calculations,\nif the methods are defined then its good for use.
        + items()
        + keys()
        + values()
    }
    Class "Slice" as sliceClass
    interface "Slice" as slice{
        +Slice(mask: Sequence[int])
        +Slice(mask: python slice)
        +next()
        +prev()
    }
    interface GroupCombinations {
        calculate(Group, operation) 
    }
    class RegularCombinations{
        
    }
    class SelectiveCombinations{
        
    }
}

package "dicechancis" {
    class Die{
    }
    class "Number Statistical" as numstat
    class "String Statistical" as strstat
    class "Cumstom Statistical" as customstat
    class "Base Statistical" as basestat
    class PoolImpl
    class BagImpl
    interface Statistical{
        + items()
        + keys()
        + values()
        + map()
        + normalize()
        + mean
        + std
        + varians
    }
    interface "Die" as die{
        + {method}<<Die manipulation functions>>
        + {method}<<Operator overloads>>
        + map(callable)
        + mean
        + std
        + varians
    }
    interface Pool{
        + extend(Die)
        + {method} <<Operator Overloads>>
    }
    interface Bag
    interface string{
        Everything that subtypes\na python.string
    }
}
package "Primitives"{
    class SortedString
}

'core
DefaultCollection ..|> collection
collection --> group
DefaultGroup ..|> group
group --> mapping
group --> slice: for selective
sliceClass ..|> slice
GroupCombinations --> group
RegularCombinations ..|> GroupCombinations
SelectiveCombinations ..|> GroupCombinations
'deck
'diechanics
Die ..|> die
Die --> Statistical 
die --|> mapping
numstat .up.|> Statistical
strstat .up.|> Statistical
customstat .up.|> Statistical
numstat -down-|> basestat: special\ncase of 
strstat -down-|> basestat: special\ncase of
customstat -down-|> basestat :special\ncase of
strstat --> string
SortedString ..|> string
Pool --|> collection
PoolImpl ..|> Pool
PoolImpl --|> DefaultCollection
Bag --|> group
BagImpl ..|> Bag
BagImpl --|> DefaultGroup
@enduml