__all__ = ["Group"]

from typing import Protocol, Self, runtime_checkable

from ttstatistics.core.protocols.mapping import Mapping


@runtime_checkable
class Group(Protocol):
	def inside(self): ...

	def keys(self): ...

	def values(self): ...

	def items(self): ...
	def __bool__(self): ...

	def __add__(self, rhs: Mapping | Self): ...
