@startuml package
package core {
     package operations{
       component combintorics
       component macro
       component micro

     }
     package protocols as core_protocols{
        component bag
        component base
        component mapping
        component pool
     }
}
package "dicechanics" as ds {
    package protocols as die_protocols{
        component die.py as protodie
        component statistical.py     
    }
    package statisticals{
        component base.py
        component scalar.py
        component string.py
    }
    component die.py
}
package "utils" as utils {
    component primitives
    component reference
}

@enduml