@startuml System
top to bottom direction
class Die{
}
class Pool{
    {method}<<Operator overloads>>
}
class Bag{
    {method}<<Operator overloads>>
}
class "Number Statistical" as numstat
class "String Statistical" as strstat
class "Cumstom Statistical" as customstat
class "Base Statistical" as basestat
interface "Die" as die{
    {method}<<Die manipulation functions>>
    {method}<<Operator overloads>>
    +map(callable)
    + mean
    + std
    + varians
}
interface "Pool" as pool {
    - bags: list[bag]
}
interface "Mapping" as mapping{
    + items()
    + keys()
    + values()
    + map()
}
interface Statistical{
    + items()
    + keys()
    + values()
    + map()
    + normalize()
    + mean
    + std
    + varians
}
interface "Bag" as bag{
    - mappings : list[Mapping]
}

Pool .|> pool
pool --> bag
Bag .|> bag
bag -down-> mapping
Die .up.|> die
Deck .up.|> mapping
Die --> Statistical 
die -up-|> mapping
numstat .up.|> Statistical
strstat .up.|> Statistical
customstat .up.|> Statistical
numstat --|> basestat: special\ncase of 
strstat --|> basestat: special\ncase of
customstat --|> basestat :special\ncase of
strstat ..> SortedString
@enduml